REPLACEMENTS = {
    "villageidiot": ["farmer", "imp"],
    "steward": ["washerwoman", "grandmother", "pixie"],
    "knight": ["washerwoman", "librarian", "soldier"],
    "shugenja": ["clockmaker", "chef", "tealady"],
    "bountyhunter": ["grandmother", "investigator", "oracle"],
    "highpriestess": ["general", "dreamer", "grandmother"],
    "balloonist": ["dreamer", "fortuneteller", "farmer"],
    "preacher": ["exorcist", "courtier", "monk"],
    "acrobat": ["juggler", "gambler", "fool"],
    "cultleader": ["empath", "dreamer", "tealady"],
    "alsaahir": ["slayer", "gossip", "juggler"],
    "nightwatchman": ["virgin", "minstrel", "huntsman"],
    "fisherman": ["artist", "savant", "farmer"],
    "banshee": ["sage", "ravenkeeper", "fool"],
    "ogre": ["goon", "moonchild", "mutant"],
    "plaguedoctor": ["sweetheart", "barber", "snitch"],
    "hatter": ["barber", "sweetheart", "snitch"],
    "politician": ["goon", "klutz", "snitch"],
    "zealot": ["butler", "golem", "snitch"],
    "harpy": ["cerenovus", "scarletwoman", "witch"],
    "widow": ["spy", "poisoner", "scarletwoman"],
    "summoner": ["pithag", "mezepheles", "eviltwin"],
    "goblin": ["fearmonger", "eviltwin", "scarletwoman"],
    "vizier": ["baron", "psychopath", "devilsadvocate"],
    "organgrinder": ["fearmonger", "devilsadvocate", "witch"],
    "boffin": ["mastermind", "baron", "pithag"],
    "yaggababble": ["shabaloth", "riot", "imp"],
    "lilmonsta": ["lleech", "pukka", "imp"],
    "kazali": ["vortox", "vigormortis", "imp"],
    "ojo": ["imp", "po", "vigormortis"],
    "lordoftyphon": ["nodashii", "imp", "leviathan"],
}

CLOCKTOWER_CON_REPLACEMENTS = {
    "villageidiot": ["farmer", "imp"],
    "shugenja": ["clockmaker", "chef", "tealady"],
    "bountyhunter": ["grandmother", "investigator", "oracle"],
    "highpriestess": ["general", "dreamer", "grandmother"],
    "alsaahir": ["slayer", "gossip", "juggler"],
    "banshee": ["sage", "ravenkeeper", "fool"],
    "ogre": ["goon", "moonchild", "mutant"],
    "plaguedoctor": ["sweetheart", "moonchild", "barber"],
    "hatter": ["barber", "sweetheart", "snitch"],
    "zealot": ["butler", "golem", "snitch"],
    "harpy": ["cerenovus", "scarletwoman", "witch"],
    "summoner": ["pithag", "mezepheles", "eviltwin"],
    "boffin": ["mastermind", "baron", "pithag"],
    "yaggababble": ["shabaloth", "riot", "imp"],
    "kazali": ["vortox", "vigormortis", "imp"],
    "ojo": ["imp", "po", "vigormortis"],
    "lordoftyphon": ["nodashii", "imp", "leviathan"],
}
